### ISSUE TITLE
Connection Serial Cable

### ISSUE THREAD

**Issue by darkat** [javierdelapuente/reeprotocol#2]
In my case i have a Spanish Electrical meter using a serial cable (without modem), and when i executed the script: 
`py .\modem_cliente.py --port="COM6" --der=1 --dir_pm=1 --clave_pm=1` 
I can't connect. I always get:
```
INFO:reeprotocol:nothing yet...
INFO:reeprotocol:iterate read thread
```
I mean that:
der = Link adress
dir_pm = mesaurement point
clave_pm = read password
is it correct? can i use a serial cable without modem?
thanks

**Comment by ecarreras** [comment]
Have you modified the `PhysicalLayer` to  only use only Serial? because the code you have to pass the number to call and it initializes the modem connection.

Maybe if you put the code we can check it

I've done a PR with IP Physical Layer.

**Comment by ecarreras** [comment]
Maybe a good implementation will be a Serial object inheriting from `PhysicalLayer` and `Modem` object inheriting from `Serial`

**Comment by javierdelapuente** [comment]
As ecarreras said, the correct implementation would be to add a Serial object, that will be very similar to the modem one.

I'd rather leave the PhysicalLayer name, because that is the name given in the specification. Although it will probably never be implemented, there are more options than serial point-to-point.
